# Generated by Django 4.0.6 on 2022-07-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='slag',
            new_name='slug',
        ),
    ]
